=== cc8461/pentext-project/dtd/servicebreakdown.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:import namespace="http://www.w3.org/2001/XInclude"
    schemaLocation="http://www.w3.org/2001/XInclude/XInclude.xsd"/>
  <xs:element name="breakdown">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="service"/>
        <xs:element ref="extra"/>
      </xs:choice>
      <xs:attributeGroup ref="xml:specialAttrs"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="service">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="specification"/>
        <xs:element minOccurs="0" ref="effort"/>
        <xs:element minOccurs="0" ref="hourly_rate"/>
        <xs:element ref="fee"/>
      </xs:sequence>
      <xs:attribute name="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>  
  <xs:element name="fee">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="max"/>
        <xs:element ref="min"/>
        <xs:element ref="computed"/>
      </xs:choice>
      <xs:attribute name="denomination" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="eur"/>
            <xs:enumeration value="gbp"/>
            <xs:enumeration value="usd"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="estimate" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="hourly_rate" type="xs:float"/>
  <xs:element name="extra">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="specification"/>
        <xs:element minOccurs="0" ref="effort"/>
        <xs:element minOccurs="0" ref="hourly_rate"/>
        <xs:element ref="fee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="specification" type="xs:string"/>
  <xs:element name="effort">
    <xs:complexType mixed="true">
      <xs:all minOccurs="0">
        <xs:element ref="max"/>
        <xs:element ref="min"/>
      </xs:all>
      <xs:attribute name="in" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="computed">
    <xs:complexType/>
  </xs:element>
  <xs:element name="min" type="xs:float"/>
  <xs:element name="max" type="xs:float"/>
</xs:schema>

=== cc8461/pentext-project/source/servicebreakdown.xml
<?xml version="1.0" encoding="UTF-8"?>
<breakdown xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../dtd/servicebreakdown.xsd">
  <service>
    <specification>Example Service 1: set duration in days and with hourly rate.</specification>
    <effort in="days">2</effort>
    <hourly_rate>10</hourly_rate>
    <fee denomination="eur">
      <computed/>
    </fee>
  </service>
  <service>
    <specification>Example Service 2: variable duration with min/max parameters and with hourly
      rate.</specification>
    <effort in="days">
      <min>3</min>
      <max>4</max>
    </effort>
    <hourly_rate>10</hourly_rate>
    <fee denomination="eur">
      <computed/>
    </fee>
  </service>
  <service>
    <specification>Example Service 3: set duration in days with CUSTOM (non-computed) set
      fee.</specification>
    <effort in="days">5</effort>
    <fee denomination="eur">500</fee>
  </service>
  <service>
    <specification>Example Service 4: set duration in hours with CUSTOM (non-computed) variable fee
      (min/max).</specification>
    <effort in="hours">4</effort>
    <fee denomination="eur">
      <min>100</min>
      <max>200</max>
    </fee>
  </service>
  <service>
    <specification>Example Service 5: set duration in days with CUSTOM (non-computed) estimated
      fee.</specification>
    <effort in="hours">4</effort>
    <fee denomination="eur" estimate="yes">1000</fee>
  </service>
  <service optional="yes">
    <specification>Example Service 6: optional service</specification>
    <effort in="days">
      <min>1</min>
      <max>2</max>
    </effort>
    <hourly_rate>50</hourly_rate>
    <fee denomination="eur">
      <computed/>
    </fee>
  </service>
  <extra>
    <specification>Example Extra Cost 1: set fee</specification>
    <fee denomination="eur">1000</fee>
  </extra>
  <extra>
    <specification>Example Extra Cost 2: variable min/max fee</specification>
    <fee denomination="eur">
      <min>1000</min>
      <max>1200</max>
    </fee>
  </extra>
  <extra>
    <specification>Example Extra Cost 3: estimated fee</specification>
    <fee denomination="eur" estimate="yes">600</fee>
  </extra>
  <extra>
    <specification>Example Extra Cost 4: with duration</specification>
    <effort in="days">6</effort>
    <fee denomination="eur">600</fee>
  </extra>
</breakdown>
